# Generated by Django 2.0.5 on 2018-11-15 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm01', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=7)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
