# Generated by Django 2.1.3 on 2018-11-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20181116_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airdata',
            old_name='pm01',
            new_name='pm1',
        ),
    ]
