# Generated by Django 2.1.3 on 2018-11-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20181123_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdata',
            name='mq135',
            field=models.DecimalField(decimal_places=0, default='300', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airdata',
            name='mq9',
            field=models.DecimalField(decimal_places=0, default='400', max_digits=4),
            preserve_default=False,
        ),
    ]
